plugins {
    id 'java-library'
    id 'net.fabricmc.fabric-loom'
}

base {
    archivesName = "${mod_id}-fabric-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    accessWidenerPath.set(file("src/main/resources/${mod_id}.accesswidener"))

    runs {
        client {
            client()
            setConfigName('Industria Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Industria Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
        dataGeneration {
            client()
            setConfigName('Industria Fabric Data Generation')
            ideConfigGenerated(true)
            runDir('runs/datagen')
            property('fabric-api.datagen', 'true')
            property('fabric-api.datagen.modid', mod_id)
            property('fabric-api.datagen.output-dir', file('src/main/generated').absolutePath)
        }
    }
}

sourceSets.main.resources.srcDir('src/main/generated')

configurations {
    commonJava {
        canBeResolved = true
        canBeConsumed = false
    }
    commonClientJava {
        canBeResolved = true
        canBeConsumed = false
    }
    commonResources {
        canBeResolved = true
        canBeConsumed = false
    }
}

def library = { String artifact ->
    "${turtymultiloader_group}:${artifact}:${turtymultiloader_version}"
}

dependencies {
    commonJava project(path: ':common', configuration: 'commonJava')
    commonClientJava project(path: ':common', configuration: 'commonClientJava')
    commonResources project(path: ':common', configuration: 'commonResources')
    compileOnly project(':common')
    clientCompileOnly project(path: ':common', configuration: 'clientApiElements')

    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    implementation library('turtymultiloader-fabric')
    include library('turtymultiloader-fabric')
    implementation library('turtymultiloader-gas-fabric')
    include library('turtymultiloader-gas-fabric')
    implementation library('turtymultiloader-multiblock-fabric')
    include library('turtymultiloader-multiblock-fabric')
    implementation library('turtymultiloader-slurry-fabric')
    include library('turtymultiloader-slurry-fabric')

    include api("teamreborn:energy:${energy_api_version}")

    implementation "org.jbox2d:jbox2d-library:${jbox2d_version}"
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('compileClientJava', JavaCompile) {
    dependsOn(configurations.commonClientJava)
    source(configurations.commonClientJava)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava, configurations.commonClientJava)
    from(configurations.commonJava)
    from(configurations.commonClientJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)

    def properties = [
        version                  : project.version,
        turtymultiloader_version: turtymultiloader_version
    ]
    inputs.properties(properties)
    filesMatching('fabric.mod.json') {
        expand(properties)
    }
}

tasks.named('jar', Jar) {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }
}
