plugins {
    id 'base'
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

allprojects {
    group = mod_group
    version = mod_version

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://api.modrinth.com/maven' }
        maven { url = 'https://maven.terraformersmc.com/releases/' }
        maven {
            url = 'https://repo.repsy.io/mvn/turtywurty/public'
            content {
                includeGroup(turtymultiloader_group)
                includeGroup('dev.turtywurty')
            }
        }
        maven { url = 'https://maven.ladysnake.org/releases' }
    }
}

tasks.named('assemble') {
    dependsOn(':common:assemble', ':fabric:assemble', ':neoforge:assemble')
}

tasks.named('check') {
    dependsOn(':common:check', ':fabric:check', ':neoforge:check')
}
